language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
 - wget http://getcomposer.org/composer.phar
 - composer install --dev

before_install:
 - git submodule update --init --recursive vendor/rabbit-project/rabbit
 
script: phpunit -c phpunit.xml.dist
