Printando conteúdo da Action:<br />
================<br />
<?= $this->content ?><br />
================<br />
Depois de printar o conteudo da Action:
<p>Capturando Conteudo salvando na variavél <strong>foo</strong>:</p> 
<pre>

	<code>Layout Thema Default</code>

</pre>


<?php $this->placeholder('foo')->captureStart() ?>
	Layout Thema Default:<br />
<?php $this->placeholder('foo')->captureEnd(); ?>


<p>Printando variável <strong>foo</strong>:</p>
<?= $this->placeholder('foo'); ?>
