<form method="POST" action="<?= $this->baseUrl('teste/index')?>">
	<p><label>Nome: </label> <input name="myObjeto[nome]" value="<?= ($this->usuario!=null)? $this->usuario->getNome() : '' ?>" /></p>
	<p>
		<label>Grupo: </label>
		<select name="myObjeto[grupo][id]">
			<option value="0" <?= $this->usuario == null ? 'selected="selected"' : '' ?>>Selecione ...</option>
			<option value="1" <?= $this->usuario != null && $this->usuario->getGrupo()->getId() == 1 ? 'selected="selected"' : '' ?>>Administrador</option>
			<option value="2" <?= $this->usuario != null && $this->usuario->getGrupo()->getId() == 2 ? 'selected="selected"' : '' ?>>Visitante</option>
		</select>
	</p>
	<p><input type="submit" value="Enviar" /> </p>
</form>